[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/tumercadovikingo/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/tumercado/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
